### ISSUE TITLE
Donkey Kong Country boots with blank flashing screen

### ISSUE THREAD

**Issue by PrgmrAtHrt** [EvilJagaGenius/jagoombacolor#1]
Unfortunately, Donkey Kong Country is not working properly. The game simply boots with a blank flashing screen.

**Comment by EvilJagaGenius** [comment]
Replicated and taking a look.

**Comment by EvilJagaGenius** [comment]
Latest commit gets DKC to boot, though the intro screens are messed up.  In-game it looks fine, so it's not game-breaking, but I'll still try to fix it properly.

**Comment by PrgmrAtHrt** [comment]
Nice! Best of luck with the rest of the fix.

**Comment by EvilJagaGenius** [comment]
Should be fixed in v0.4, closing the issue.
