### ISSUE TITLE
Super Mario Land DX save not working

### ISSUE THREAD

**Issue by PrgmrAtHrt** [EvilJagaGenius/jagoombacolor#16]
Unfortunately, the new Super Mario Land DX romhacks' saves do not seem to work properly with goomba. With what debugging I did, I found that there is something bugging out and erroneously triggering sram saves to fill the entirety of sram with nothing. I'm not savvy enough to take it beyond this point, which is why i'm reporting it here.

**Comment by radimerry** [comment]
https://github.com/radimerry/jagoombacolor/commit/11087cf9cc453119eac9f0edd25de0d086be967a
- Think I got it. By default, SRAM is disabled on maybe most or all mappers?
- Game is trying to clear all of RAM at startup but SRAM should be write-protected.

**Comment by PrgmrAtHrt** [comment]
@radimerry That fixed it! Well done, and thank you!

**Comment by EvilJagaGenius** [comment]
Merged and should be fixed in v0.5, closing the issue.
