### ISSUE TITLE
Pokemon Prism freezes

### ISSUE THREAD

**Issue by Sakitoshi** [EvilJagaGenius/jagoombacolor#2]
when the game tries to show the map change sign (when moving from a town to a route for example), it freezes.
also tested pokemon crystal clear and the same sign it's displayed garbled with goomba mode enabled. without goomba mode it shows fine but when in a pokemon battle the top left border of text windows show a different tile (seems to be from the exp bar).

**Comment by EvilJagaGenius** [comment]
Haven't replicated this specific bug.  I have Prism v0.94.0237 and it freezes for me after riding the mine cart... it might be similar, so I'll look into it.

Crystal has the same issue with the EXP bar tile in the text box.  I can take a look but it's not game-breaking.  Was not able to replicate the garbled sign in Crystal Clear yet.

**Comment by Sakitoshi** [comment]
it's definitely the map change sign for prism.
I have a save inside of the professor house and it freezes as soon as it shows something on the screen. what is the first thing that shows up? the sign. the sign also appears when you get off of the mine cart.
I can further confirm this because in trying to get crystal to work on goomba (from that thread on dwedit's forum), I copy/pasted prism code for the sign in crystal and it freezes whenever it shows up. here's the code Sakitoshi/pokecrystal@62e74a04aaae71b09b2d3cacd6b825866621a5b6
for crystal clear you have to activate goomba mode by hex editing the rom and change the 0x3fff byte from 00 to 01, you'll see a G top right on the main menu.

**Comment by EvilJagaGenius** [comment]
Latest commit seems to fix Prism on my end, after riding the mine cart, a sign pops up at the bottom of the screen and the game keeps running.

**Comment by Sakitoshi** [comment]
yes, can confirm that prism doesn't freeze anymore.
dunno if it was happening before, but crystal clear isn't playing pokemon animations.
and pokemon stats are completely broken on pokemon crystal and derivates.

**Comment by EvilJagaGenius** [comment]
Should be fixed in v0.4, closing the issue.
